services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    hostname: elastic-search
    container_name: elastic-search
    networks:
      - elastic-search

networks:
  elastic-search:
    driver: bridge
