services:
  gotenberg:
    image: gotenberg/gotenberg:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    hostname: gotenberg
    container_name: gotenberg

networks:
  gotenberg:
    driver: bridge