services:
  mysql:
    image: mysql:8.0
    restart: always
    cap_add:
      - ALL
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle123!@#
      - MYSQL_ROOT_PASSWORD=root123!@#
    ports:
      - '3306:3306'
    hostname: moodle-mysql
    container_name: moodle-mysql
    networks:
      - moodle

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    environment:
      - PMA_HOST=moodle-mysql
      - PMA_PORT=3306
      - PMA_USER=moodle
      - PMA_PASSWORD=moodle123!@#
      - MYSQL_ROOT_PASSWORD=root123!@#
    ports:
      - '8080:80'
    hostname: moodle-phpmyadmin
    container_name: moodle-phpmyadmin
    depends_on:
      - mysql
    networks:
      - moodle

  moodle:
    image: moodle:v4.0.4
    restart: unless-stopped
    volumes:
      - ./moodle:/var/www/html
      - ./data:/home/moodle/data
    environment:
      - MOODLE_DB_TYPE=mysqli
      - MOODLE_DB_HOST=moodle-mysql
      - MOODLE_DB_PORT=3306
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=moodle123!@#
      - MOODLE_DB_PREFIX=md_
      - MOODLE_SITE_URL=http://localhost
      - MOODLE_DATA_PATH=/home/moodle/data
    ports:
      - '80:80'
    hostname: moodle
    container_name: moodle
    depends_on:
      - mysql
    networks:
      - moodle

networks:
  moodle:
    driver: bridge
