services:
  mysql:
    image: mysql:8.4.1
    restart: always
    cap_add:
      - ALL
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento123!@#
      - MYSQL_ROOT_PASSWORD=root123!@#
    ports:
      - '3306:3306'
    hostname: magento-mysql
    container_name: magento-mysql
    networks:
      - magento

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    environment:
      - PMA_HOST=magento-mysql
      - PMA_PORT=3306
      - PMA_USER=magento
      - PMA_PASSWORD=magento123!@#
      - MYSQL_ROOT_PASSWORD=root123!@#
    ports:
      - '8080:80'
    hostname: magento-phpmyadmin
    container_name: magento-phpmyadmin
    depends_on:
      - mysql
    networks:
      - magento

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    volumes:
      - search_data:/usr/share/elasticsearch/data
    environment:
      - node.name=magento-elastic-search
      - discovery.type=single-node
      - discovery.seed_hosts=magento-elastic-search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    hostname: magento-elastic-search
    container_name: magento-elastic-search
    networks:
      - magento

  magento:
    image: magento:v2
    restart: unless-stopped
    volumes:
      - magento:/var/www/html
    environment:
      - ADMIN_URL=admin
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_FIRST_NAME=Magento
      - ADMIN_LAST_NAME=Commerce
      - ADMIN_EMAIL=magento@commerce.com
      - ADMIN_USE_SECURE=0
      - ADMIN_SECURITY_KEY=0

      - DB_HOST=magento-mysql:3306
      - DB_NAME=magento
      - DB_USER=magento
      - DB_PASSWORD=magento123!@#
      - DB_PREFIX=
      - ES_HOST=
      - ES_PORT=
      - ES_USERNAME=
      - ES_PASSWORD=

      - MAGENTO_URL=http://localhost/
      - MAGENTO_SECURE_URL=http://localhost/
      - MAGENTO_LANGUAGE=en_US
      - MAGENTO_CURRENCY=USD
      - MAGENTO_TIMEZONE=UTC
      - MAGENTO_USE_REWRITES=0
      - MAGENTO_USE_SECURE=0
      - MAGENTO_MODE=developer
      - MAGENTO_SESSION_SAVE=db
      - MAGENTO_SAMPLE_DATA=1
    ports:
      - '80:80'
    hostname: magento
    container_name: magento
    depends_on:
      - mysql
      - elastic-search
    networks:
      - magento

volumes:
  mysql_data:
    driver: local
  magento:
    driver: local
  search_data:
    driver: local

networks:
  magento:
    driver: bridge
